const genresData = [
    "Fiction",
    "Science Fiction",
    "Mystery",
    "Novel",
    "Historical Fiction",
    "Fantasy",
    "Memoir",
    "Biography",
    "Romance",
    "Horror",
    "Humor",
    "True Crime",
    "Adult",
    "Action",
    "Adventure",
    "Young Adult",
    "Paranormal",
    "Dystopia",
    "Thriller",
    "Post Apocalyptic",
    "Literary Fiction",
    "Magical Realism",
    "Self-Help",
]

export default genresData;